### ISSUE TITLE
Is it normal to run an example in minutes of key-gen task?

### ISSUE THREAD

**Issue by xyyimian** [NingMiao/CGMH#10]
I tried the two examples in the key-gen task. It takes several minutes on 1080-Ti to finish. I am wondering if it is normal or if there is some way to efficiently decrease forward time so that the input file could be of several MB.

**Comment by NingMiao** [comment]
CGMH is not as fast as forward sampling, but it won't take several minutes for only two examples. Please make sure that you are not running on CPU, and memory exchange between GPU and CPU is not a bottleneck. If it doesn't work, try decrease the sampling time for each sample. In some tasks, you only need about 20 steps to get satisfactory results.
